"""Orthomosaic output adapter.

Final GeoTIFF orthomosaic generation requires dense geometry or trusted camera
poses. This module provides graceful reduced-output behavior until those stages
are available.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class OrthomosaicResult:
    success: bool
    output_path: Path | None = None
    preview_path: Path | None = None
    message: str = ""


def generate_orthomosaic_placeholder(output_dir: Path, enabled: bool = False) -> OrthomosaicResult:
    output_dir.mkdir(parents=True, exist_ok=True)
    if not enabled:
        return OrthomosaicResult(
            success=False,
            output_path=output_dir / "orthomosaic.tif",
            message="Orthomosaic disabled by profile/options.",
        )
    return OrthomosaicResult(
        success=False,
        output_path=output_dir / "orthomosaic.tif",
        message="Orthomosaic requires successful SfM/MVS and is not generated by the reduced pipeline.",
    )
